on: [push]
name: basic_workflow # the name for this workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: Login to AzureCloud with Az Powershell
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }} # Be sure to have this variable in repo level
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }} # Be sure to have this variable in repo level
            username: ${{ secrets.REGISTRY_USERNAME }} # Be sure to have this variable in repo level
            password: ${{ secrets.REGISTRY_PASSWORD }} # Be sure to have this variable in repo level
        # replace #APP# for the name of the container app you are building and pushing
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/#APP#:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/#APP#:${{ github.sha }}